name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.18.0

    - name: Navigate to frontend directory
      run: cd vite-project

    - name: Install dependencies
      run: |
        cd vite-project   # Make sure we are in the 'frontend' directory
        npm install   # Install frontend dependencies

    - name: Build project
      run: |
        cd vite-project   # Navigate to the frontend directory if needed
        npm run build # Build the frontend app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: vite-project/dist
        target_branch: gh-pages